title: CV | 김언지의 resume
description: 김언지의 resume
url: https://birdust.github.io/resume/
baseurl: ""
theme_skin: blue

future: true

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-minifier

exclude:
  - docker-compose.yml
